export enum CountyType {
  Norrbotten = 'Norrbotten',
  Västerbotten = 'Västerbotten',
  Jämtland = 'Jämtland',
  Västernorrland = 'Västernorrland',
  Dalarna = 'Dalarna',
  Gävleborg = 'Gävleborg',
  Värmland = 'Värmland',
  Örebro = 'Örebro',
  Västmanland = 'Västmanland',
  Uppsala = 'Uppsala',
  Stockholm = 'Stockholm',
  Södermanland = 'Södermanland',
  Västragötaland = 'Västragötaland',
  Östergötland = 'Östergötland',
  Jönköping = 'Jönköping',
  Kalmar = 'Kalmar',
  Kronoberg = 'Kronoberg',
  Halland = 'Halland',
  Skåne = 'Skåne',
  Blekinge = 'Blekinge',
  Gotland = 'Gotland',
}
